theme:minima
Title: Mój Pierwszy Blog na Gicie
author: Grzegorz Mekal
email: gmekal@protonmail.com
Desiption: > # this means to ignore newlines until "baseurl:"
 

# social links
twitter_username: mandraghor # DO NOT include the @ character, or else the build will fail!
github_username: mandraghor # DO NOT include the @ character, or else the build will fail!

show_excerpts: true 
